# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ff007ee126a042f06bdf4c08f8e2df510b486bda8e74f6d8880621a90553c69db4d68a3d828df74ced3397dc989a65527b30452663518304819e58ac31a60a

test:
  secret_key_base: c1394d55c2277e808bca56f78bc3f139e0e7f550bcbf67ad660221f98b516a77977ca64df8b898a2f35db28bb5fe112bd71793f023a46f7edcb2ff7fbf851b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
